apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskapp
  name: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskapp
    spec:
      containers:
      - image: anuja9431/helloworld:1
        name: flaskapp
        resources: {}
status: {}


---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskapp